### ISSUE TITLE
Excluding taxa not present in all files

### ISSUE THREAD

**Issue by weedcentipede** [nylander/catfasta2phyml#2]
Hi, 
I was wondering if the tools have any option for exclude the taxa that's not present in all the files, 

Thanks in advance, 
Luis.

**Comment by nylander** [comment]
I don't think so no. The tool was not developed with that in mind. It's a good suggestion for an extra feature, however, so thank you Luis!

**Comment by nylander** [comment]
This behavior is now implemented in the program (commit 6bad419). Try this:

`catfasta2phyml.pl  --intersect *.fas  > combine_taxa_present_in_all_files.phy`
