### ISSUE TITLE
Output also the position of original alignments withing the concatenated alignment

### ISSUE THREAD

**Issue by AlesBucek** [nylander/catfasta2phyml#3]
Not an issue, rather a suggestion: it would be great if catfasta2phyml would be outputting also the positions of the individual alignments in the concatenated alignment.
E.g. if 1st alignment is 100 and 2nd alignment 200 characters long, the additional output file would continue following info:
Alignment1.fasta 1   100
Alignment2.fasta 101   300
...which could be used for e.g. defining the partitions for downstream phylogeny reconstruction using the concatenated alignment.
(I was using FASconCAT by Patrick Kueck can do this but seems to be much slower than your tool)
Best,
Ales

**Comment by nylander** [comment]
Thank you Ales for your suggestion. And I know, it is indeed a good feature to have - and it have actually been on my todo list (for a long time). For some reason I can't remember, I did not include that feature immediately, but settled with some basic info that might help you construct such info on your own.

If you run the script with the option `--verbose`, the info on the size of individual input files is printed to standard error (see example below). You have to do the summation on your own for now I'm afraid.

```
$ catfasta2phyml.pl --verbose m*d.fas > apa

Checking sequences in infiles...

  File m1d.fas:  ntax=23 nchar=1303
  File m2d.fas:  ntax=23 nchar=1042
  File m3d.fas:  ntax=23 nchar=394

Checked 3 files -- sequence labels and lengths seems OK.
Concatenated 23 sequences, total length 2739.
Printing concatenation to STDOUT.


End of script.


```

**Comment by nylander** [comment]
This table is now the output (STDERR) from the program (commit  6bad419).

Recommended usage:

`catfasta2phyml.pl  *.fas  >  combined.phy  2>  combined_partitions.txt`
