### ISSUE TITLE
Concatenated alignment in .xmfa format?

### ISSUE THREAD

**Issue by juliaped** [nylander/catfasta2phyml#4]
Hi, 
I found your tool a few weeks ago and it has helped me a lot! However I was wondering, is it possible to get the output/concatenated alignment in .xmfa format? If not, do you know of some other tool for that?

Thanks in advance, 
Julia

**Comment by nylander** [comment]
Dear @juliaped 
Thank you for your message. Very late reply I'm afraid.
It is not possible to output the concatenated data in a [xmfa](https://bioperl.org/formats/alignment_formats/XMFA_multiple_alignment_format.html) format, and to be honest I can't see exactly what the input should look like for this to happen.
The software MAUVE uses ["a Non-standard XMFA format"](http://darlinglab.org/mauve/user-guide/files.html), and perhaps there might be more information regarding your issue if looking in that direction?
Cheers
Johan
